### ISSUE TITLE
Error message when opening several files

### ISSUE THREAD

**Issue by benoistlaurent** [HubLot/vim-gromacs#10]
Got this error message when I open several gromacs file in the same time.
It does not alter vi operation but it's very annoying.

Exemple:
$ vi toto.itp tata.ipt

Error detected while processing /Users/benoist/.vim/ftplugin/gromacs.vim:
line   48:
E122: Function GromacsCommentSelection already exists, add ! to replace it
line   61:
E122: Function GromacsUncommentSelection already exists, add ! to replace it
line   71:
E122: Function GromacsMoveSection already exists, add ! to replace it
Press ENTER or type command to continue

**Comment by HubLot** [comment]
It should fix the problem.
Thanks to @Reinis and @jbarnoud
