### ISSUE TITLE
expanding mdp coloring

### ISSUE THREAD

**Issue by benoistlaurent** [HubLot/vim-gromacs#15]
I use a personnal format that is very close to mdp but the comment character is '#'.
Hence, I'd like to use mdp color syntaxing with these files by adding these lines to my vimrc

au BufRead,BufNewFile *.msp set filetype=mdp
au BufRead,BufNewFile *.msp syn match mdpComment "#.*$"

It works well but I have this message when I open a file :

/path/to/ftplugin/mdp.dict
Press ENTER or type command to continue

How can I remove it?

**Comment by HubLot** [comment]
I can't reproduce your bug.
The mdp coloring for msp files works well on my side.

What is the version of Vim ? Operating System ?
The completion works with "Ctrl+N" ?

**Comment by jbarnoud** [comment]
I just tried and it works on my computer. Do you have the /path/to/ftplugin/mdp.dict file ?

**Comment by benoistlaurent** [comment]
For some unknown reason, it seems to work fine finally.
I'll let you know if something's wrong.

2012/10/22 jbarnoud notifications@github.com

> I just tried and it works on my computer. Do you have the
> /path/to/ftplugin/mdp.dict file ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HubLot/vim-gromacs/issues/15#issuecomment-9660238.

## 

Benoist Laurent -- PhD Student
benoist.laurent@gmail.com
Laboratoire de Biochimie Theorique / CNRS UPR 9080
Institut de Biologie Physico-Chimique
13, rue Pierre et Marie Curie
F-75005 Paris
Tel. +33 [0]1 58 41 51 67 or +33 [0]6 21 64 50 56
