### ISSUE TITLE
comments coloring bug

### ISSUE THREAD

**Issue by benoistlaurent** [HubLot/vim-gromacs#16]
Hey,

I realized that inline comments are not considered as comments vi (not colored well).
Example : 
nsteps                         = 50000 ; 100 ps
==> 100 ps is colored as 50000

**Comment by HubLot** [comment]
Hum strange...
It Works with me.
Which is your version of vim ?

**Comment by benoistlaurent** [comment]
VIM - Vi IMproved 7.2

**Comment by jbarnoud** [comment]
I seem affected too.

**Comment by HubLot** [comment]
In fact, I wasn't affected because I didn't have the latest version set... My bad.
With the last version, i have the same bug.
But the fix of Jonathan resolve this bug.
