### ISSUE TITLE
Section color code is not consistent between ndx and top

### ISSUE THREAD

**Issue by jbarnoud** [HubLot/vim-gromacs#3]
In bracket section names are not colored the same in ndx and top files. They use the "constant" style in ndx files and the "Keyword" one in top. The brackets are not consistent neither. They use "Special" style in ndx and "Function" in top.

**Comment by HubLot** [comment]
Indeed, since I did one after the other, I didn't check if they had the same color.
I'll replace the colors of ndx by those of top (The opposite will be bad due to the others colors of the top files).

**Comment by HubLot** [comment]
Done!
